prgrms-web-devcourse-final-project/WEB3_4_DAJAVA_BE

.idea/WEB3_4_DAJAVA_BE.iml
.idea/checkstyle-idea.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
.idea/workspace.xml
backend/src/main/java/com/dajava/backend/domain/event/repository/PointerClickEventRepository.java
backend/src/main/java/com/dajava/backend/domain/event/repository/PointerMoveEventRepository.java
backend/src/main/java/com/dajava/backend/domain/event/repository/PointerScrollEventRepository.java
backend/src/main/java/com/dajava/backend/domain/event/repository/SessionDataRepository.java
backend/src/main/java/com/dajava/backend/domain/event/service/EventLogService.java
backend/src/main/java/com/dajava/backend/domain/event/service/EventLogServiceImpl.java
backend/src/main/java/com/dajava/backend/domain/home/event/PointerClickEvent.java
backend/src/main/java/com/dajava/backend/domain/home/event/PointerMoveEvent.java
backend/src/main/java/com/dajava/backend/domain/home/event/PointerScrollEvent.java
backend/src/main/java/com/dajava/backend/domain/home/event/SessionData.java
backend/src/main/java/com/dajava/backend/domain/home/repository/PointerClickEventRepository.java
backend/src/main/java/com/dajava/backend/domain/home/repository/PointerMoveEventRepository.java
backend/src/main/java/com/dajava/backend/domain/home/repository/PointerScrollEventRepository.java
backend/src/main/java/com/dajava/backend/domain/home/repository/SessionDataRepository.java
backend/src/main/java/com/dajava/backend/domain/home/service/EventLogService.java
backend/src/main/java/com/dajava/backend/domain/home/service/EventLogServiceImpl.java

로그 이벤트 도메인 기본 작업

---

backend/src/main/java/com/dajava/backend/domain/solution/service/SolutionServiceImpl.java
backend/src/main/java/com/dajava/backend/global/config/GeminiApiConfig.java
backend/src/main/java/com/dajava/backend/global/exception/ErrorCode.java

<br/>
closes #26
<br/>
- 잘못 설정된 if문의 조건 수정
- 정확한 에러 파악 위해 에러코드 추가 및 적용
<br/>
<br/>
<br/>

fix: 기존에 잘못 설정되어있던 예외처리 조건(register.isServiceExpired())값 변경 및 에러 코드 추가

---

backend/src/main/java/com/dajava/backend/domain/solution/scheduler/SolutionScheduler.java
backend/src/main/java/com/dajava/backend/domain/solution/service/SolutionServiceImpl.java
backend/src/main/java/com/dajava/backend/global/config/GeminiApiConfig.java

<br/>
<br/>
- 가독성 및 이해력 향상을 위한 JavaDoc 문서 작성
<br/>
- 문서 작성의 가독성 위주로 봐주시면 감사하겠습니다.
<br/>
<br/>

docs: JavaDoc 문서 작성

---

.github/workflows/build.yml
.github/workflows/deploy.yml

<br/>
패키지 생성 및 도커 이미지를 푸시하도록 깃허브 액션을 수정하였습니다.

[CHORE] : build.yml 파일 수정

---

.github/workflows/deploy.yml
backend/src/main/java/com/dajava/backend/domain/register/converter/RegisterConverter.java

<br/>
- EventState 기본 값에 대한 처리를 일부 수정하였습니다.
- 지난 PR에 올라가지 않았던 사소한 부분이며, build.yml은 무시하셔도 좋습니다.

[FEAT] Register 관련 간단한 로직 수정

---

backend/Dockerfile
backend/src/main/java/com/dajava/backend/domain/register/controller/RegisterController.java
backend/src/main/resources/application-prod.yml
backend/src/test/java/com/dajava/backend/domain/register/controller/RegisterControllerTest.java

<br/>
- 배포 버전에 엘라스틱 서치를 적용하고, 도커 빌드를 할 수 있도록 수정

chore : 도커 파일 및 엘라스틱 서치 세팅값 변경

---

backend/build.gradle
backend/src/main/java/com/dajava/backend/global/config/CorsConfig.java
backend/src/main/java/com/dajava/backend/global/config/SpringdocConfig.java
backend/src/main/java/com/dajava/backend/global/config/WebConfig.java
backend/src/main/java/com/dajava/backend/global/filter/LogRequestFilter.java
backend/src/main/resources/application-prod.yml
backend/src/main/resources/application.yml

- 배포용으로 MySQL과 ES 세팅을 변경하였습니다.

chore : 배포용 세팅으로 변경

---

backend/src/main/java/com/dajava/backend/global/filter/LogRequestFilter.java

fix: filter 버그 수정

---

backend/src/main/java/com/dajava/backend/domain/register/service/RegisterService.java
backend/src/main/java/com/dajava/backend/global/config/DevSpringdocConfig.java
backend/src/main/java/com/dajava/backend/global/config/WebConfig.java
backend/src/main/java/com/dajava/backend/global/initdata/InitData.java
backend/src/main/resources/application-prod.yml

<br/>
- 로컬 개발 시에 h2-console과 swagger를 이용하기 불편했던 점을 개선하였습니다.
- Init Data 등록 시에 이미 존재하는 경우에 발생하는 Exception을 해결하였습니다.
- Register 등록 시, Register가 캐시에 바로 올라가도록 수정하였습니다.

[CHORE] 배포 및 테스트를 위한 코드 수정

---

backend/src/main/java/com/dajava/backend/global/filter/LogRequestFilter.java
backend/src/test/java/com/dajava/backend/domain/heatmap/controller/HeatmapControllerTest.java
backend/src/test/java/com/dajava/backend/domain/heatmap/service/HeatmapServiceImplTest.java
backend/src/test/java/com/dajava/backend/domain/register/controller/RegisterControllerTest.java
backend/src/test/java/com/dajava/backend/domain/register/service/RegisterCacheServiceTest.java
backend/src/test/java/com/dajava/backend/domain/register/service/RegisterServiceTest.java
backend/src/test/java/com/dajava/backend/domain/register/service/pageCapture/FileStorageServiceTest.java

<br/>
- 이미지 멀티파트 로직 변경으로 인해 테스트 수정
- 필터에서 요청이 필터링될시 응답 메시지가 ? 로 나오는 오류 해결 (UTF-8 설정)
<br/>
성공시 성공 여부, 메시지, 저장 경로 반환
실패시 text/plain 값으로 실패 메시지 반환

[TEST] : 로직 변경으로 인해 테스트 수정 & 필터 수정

---

backend/src/main/java/com/dajava/backend/domain/heatmap/service/HeatmapServiceImpl.java
backend/src/main/java/com/dajava/backend/domain/image/controller/ImageController.java
backend/src/test/java/com/dajava/backend/domain/heatmap/service/HeatmapServiceImplTest.java

- 기존 MySQL에서 가져오던 SolutionEvent를 ES 접근으로 변경
- Register의 URL로 이벤트 필터링 
- 테스트 코드 ES 접근으로 변경

[REFACTOR] : 리포지드 접근 ES로 변경 & 단일 URL 이벤트 필터링

---

backend/build.gradle
backend/src/main/java/com/dajava/backend/BackendApplication.java
backend/src/main/java/com/dajava/backend/domain/email/EmailService.java
backend/src/main/java/com/dajava/backend/domain/register/service/RegisterService.java
backend/src/main/java/com/dajava/backend/domain/solution/service/SolutionServiceImpl.java
backend/src/main/java/com/dajava/backend/global/component/email/MailProperties.java
backend/src/main/java/com/dajava/backend/global/config/MailConfig.java
backend/src/main/resources/application.yml
backend/src/test/java/com/dajava/backend/domain/email/service/EmailServiceTest.java
backend/src/test/java/com/dajava/backend/domain/event/scheduler/EventBufferSchedulerTest.java
backend/src/test/java/com/dajava/backend/domain/event/service/EventBatchServiceTest.java

- 이메일 발송 로직 작성
- 솔루션 신청 및 완료시 이메일 송신
- 테스트 작성
- 기존 테스트에서 오류 부분 수정

[FEAT] : 이메일 관련 기능

---

backend/src/main/java/com/dajava/backend/domain/email/AsyncEmailSender.java
backend/src/main/java/com/dajava/backend/domain/email/EmailService.java
backend/src/main/java/com/dajava/backend/global/config/AsyncConfig.java

<br/>
- 비동기 처리가 적용되지 않던 문제를 해결했습니다.
<br/>

[REFACTOR] : Async 미적용 문제 해결

---

backend/src/main/java/com/dajava/backend/domain/register/entity/Register.java
backend/src/main/java/com/dajava/backend/global/component/scheduler/SchedulerInitializer.java
backend/src/test/java/com/dajava/backend/domain/email/service/EmailServiceTest.java
backend/src/test/java/com/dajava/backend/domain/heatmap/service/HeatmapServiceImplTest.java
backend/src/test/java/com/dajava/backend/domain/register/controller/RegisterControllerTest.java
backend/src/test/java/com/dajava/backend/domain/register/service/RegisterServiceTest.java

- 테스트 수정
- Register의 pageCapture에 Builder.Default 추가
- Register Cache의 스케줄링에서 테스트를 원할하게 하기 위해 매 캐싱마다 모든 Register 데이터 넣도록 변경

[REFACTOR] : 테스트 수정 , 일부 로직 보완

---

backend/src/main/java/com/dajava/backend/domain/image/service/pageCapture/FileCleanupService.java
backend/src/main/java/com/dajava/backend/domain/image/service/pageCapture/FileStorageService.java
backend/src/main/java/com/dajava/backend/domain/register/repository/PageCaptureDataRepository.java
backend/src/main/java/com/dajava/backend/domain/register/scheduler/RegisterDataCleanupScheduler.java
backend/src/main/java/com/dajava/backend/global/initdata/InitData.java
backend/src/main/resources/application.yml
backend/src/test/java/com/dajava/backend/domain/email/service/EmailServiceTest.java
backend/src/test/java/com/dajava/backend/domain/register/service/RegisterServiceTest.java
backend/src/test/java/com/dajava/backend/domain/register/service/pageCapture/FileStorageServiceTest.java

<br/>
- 관련 없는 이미지 삭제 로직
- 테스트 실패 수정 (인자 호출 문제 등)

[REFACTOR] : 관련 없는 이미지 삭제 로직, 테스트 수정

---

backend/src/main/java/com/dajava/backend/domain/log/service/SessionServiceImpl.java

isinactive 수정
<br/>
closes #70 
<br/>
- 기능에서 어떤 부분이 구현되었는지 설명해주세요.
- 코드 로직이나 주요 변경 사항에 대해 간단히 기술하세요.
<br/>
- SessionServiceimpl expireSession 수정
<br/>
<br/>

fix: expire 만료 boolean 값 변경 -> 반대로 되어 있음 isinactive가 true로 수정

---

backend/src/main/java/com/dajava/backend/domain/event/es/scheduler/vaildation/EsEventValidateScheduler.java
backend/src/main/java/com/dajava/backend/domain/log/scheduler/SessionScheduler.java
backend/src/main/java/com/dajava/backend/global/component/analyzer/BufferSchedulerProperties.java
backend/src/main/java/com/dajava/backend/global/component/analyzer/ValidateSchedulerProperties.java

<br/>
closes #
<br/>
- 기능에서 어떤 부분이 구현되었는지 설명해주세요.
- 코드 로직이나 주요 변경 사항에 대해 간단히 기술하세요.
<br/>
<br/>
<br/>

fix : prop 통합

---

backend/src/main/java/com/dajava/backend/domain/event/es/entity/SessionDataDocument.java
backend/src/main/java/com/dajava/backend/global/initdata/InitData.java

<br/>
closes #
<br/>
- 기능에서 어떤 부분이 구현되었는지 설명해주세요.
- 코드 로직이나 주요 변경 사항에 대해 간단히 기술하세요.
<br/>
<br/>
<br/>

refactor: AI 솔루션 생성 스케줄러 작동

---

backend/src/main/java/com/dajava/backend/domain/heatmap/service/HeatmapServiceImpl.java
backend/src/main/java/com/dajava/backend/domain/image/controller/ImageController.java
backend/src/main/java/com/dajava/backend/domain/image/service/pageCapture/FileStorageService.java

[REFACTOR] : image 조회시 이미지 호출 문제 수정

---

backend/src/main/java/com/dajava/backend/domain/event/es/scheduler/vaildation/EsEventValidateScheduler.java
backend/src/main/java/com/dajava/backend/domain/image/service/pageCapture/FileStorageService.java
backend/src/main/java/com/dajava/backend/domain/register/service/RegisterService.java

<br/>
- base64 디코딩 후 이미지 저장하는 로직에서 중복 로직 분리
<br/>

[REFACTOR] 이미지 저장 로직 리팩토링

---

backend/src/main/java/com/dajava/backend/domain/log/service/EventServiceImpl.java
backend/src/main/java/com/dajava/backend/global/config/CacheConfig.java
backend/src/main/java/com/dajava/backend/global/initdata/InitData.java

- initdata FHD 기준으로 좌표값 수정
- 랜덤 범위값 합산에서 음수 또는 전체 화면을 벗어날 경우 고정값 반환
- 히트맵 캐시 생성후 유효기간 5분으로 설정 (테스트 용이성을 위함)
- 이벤트 로그 주석처리
<br/>

[REFACTOR] : initdata 수치 조정, 히트맵 캐시 만료 5분 설정

---

backend/src/main/java/com/dajava/backend/global/initdata/InitData.java

<br/>
closes #
<br/>
- 기능에서 어떤 부분이 구현되었는지 설명해주세요.
- 코드 로직이나 주요 변경 사항에 대해 간단히 기술하세요.
<br/>
<br/>
<br/>

refactor: initData 생성 로직 수정
